"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/avatar.gltf
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three"; // Add this import statement

export function Avatar(props) {
  console.log(props);

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/avatar.gltf");

  const { page } = props;
  const { actions, names } = useAnimations(animations, group);

  //FUNCS

  const handleShakeHand = () => {
    if (page === "about") {
      const { [names[0]]: animationIdle, [names[1]]: animationShakeHand } =
        actions;

      animationIdle.stop();

      animationShakeHand.reset().fadeIn(0.5).play();
      animationShakeHand.setLoop(THREE.LoopOnce);
      animationShakeHand.clampWhenFinished = true;

      let id = setTimeout(() => {
        animationIdle.reset().fadeIn(0.5).play();
      }, 3000);
      return () => {
        return id;
      };
    }
  };

  //USEFFECT
  useEffect(() => {
    const { [names[0]]: animationIdle, [names[2]]: animationWave } = actions;
    if (page === "about") {
      animationWave.reset().fadeIn(0.5).play();
      animationWave.setLoop(THREE.LoopOnce);
      animationWave.clampWhenFinished = true;

      const onAnimationFinish = () => {
        animationIdle.reset().fadeIn(0.5).play();

        animationWave
          .getMixer()
          .removeEventListener("finished", onAnimationFinish);
      };

      animationWave.getMixer().addEventListener("finished", onAnimationFinish);

      return () => {
        animationWave.stop();
      };
    } else {
      animationWave.reset().play();
    }
  }, [page]);

  return (
    <group ref={group} {...props} dispose={null} onClick={handleShakeHand}>
      <group name="Scene">
        <group
          name="Armature002"
          position={[-0.004, 0.001, 0.03]}
          rotation={[-0.026, 0.023, -0.003]}
        >
          <primitive object={nodes.Hips} />
          <group name="Body">
            <skinnedMesh
              name="Hair001baked015"
              geometry={nodes.Hair001baked015.geometry}
              material={materials.M00_001_01_Shoes_01_CLOTH}
              skeleton={nodes.Hair001baked015.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_1"
              geometry={nodes.Hair001baked015_1.geometry}
              material={materials.M00_000_HairBack_00_HAIR}
              skeleton={nodes.Hair001baked015_1.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_2"
              geometry={nodes.Hair001baked015_2.geometry}
              material={materials.F00_000_Hair_00_HAIR_01}
              skeleton={nodes.Hair001baked015_2.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_2.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_3"
              geometry={nodes.Hair001baked015_3.geometry}
              material={materials.F00_000_Hair_00_HAIR_02}
              skeleton={nodes.Hair001baked015_3.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_3.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_4"
              geometry={nodes.Hair001baked015_4.geometry}
              material={materials.M00_000_00_FaceBrow_00_FACE}
              skeleton={nodes.Hair001baked015_4.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_4.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_4.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_5"
              geometry={nodes.Hair001baked015_5.geometry}
              material={materials.M00_000_00_FaceMouth_00_FACE}
              skeleton={nodes.Hair001baked015_5.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_5.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_5.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_6"
              geometry={nodes.Hair001baked015_6.geometry}
              material={materials.M00_000_00_EyeIris_00_EYE}
              skeleton={nodes.Hair001baked015_6.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_6.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_6.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_7"
              geometry={nodes.Hair001baked015_7.geometry}
              material={materials.M00_000_00_EyeHighlight_00_EYE}
              skeleton={nodes.Hair001baked015_7.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_7.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_7.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_8"
              geometry={nodes.Hair001baked015_8.geometry}
              material={materials.M00_000_00_EyeWhite_00_EYE}
              skeleton={nodes.Hair001baked015_8.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_8.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_8.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_9"
              geometry={nodes.Hair001baked015_9.geometry}
              material={materials.M00_000_00_Face_00_SKIN}
              skeleton={nodes.Hair001baked015_9.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_9.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_9.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_10"
              geometry={nodes.Hair001baked015_10.geometry}
              material={materials.M00_000_00_FaceEyelash_00_FACE}
              skeleton={nodes.Hair001baked015_10.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_10.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_10.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_11"
              geometry={nodes.Hair001baked015_11.geometry}
              material={materials.M00_000_00_FaceEyeline_00_FACE}
              skeleton={nodes.Hair001baked015_11.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_11.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_11.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_12"
              geometry={nodes.Hair001baked015_12.geometry}
              material={materials.M00_000_00_EyeExtra_01_EYE}
              skeleton={nodes.Hair001baked015_12.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_12.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_12.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_13"
              geometry={nodes.Hair001baked015_13.geometry}
              material={materials.M00_001_01_Body_00_SKIN}
              skeleton={nodes.Hair001baked015_13.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_13.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_13.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Hair001baked015_14"
              geometry={nodes.Hair001baked015_14.geometry}
              material={materials.M00_001_01_Tops_01_CLOTH}
              skeleton={nodes.Hair001baked015_14.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_14.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_14.morphTargetInfluences
              }
            />
            {/* <skinnedMesh
              name="Hair001baked015_15"
              geometry={nodes.Hair001baked015_15.geometry}
              material={materials.M00_001_01_Bottoms_01_CLOTH}
              skeleton={nodes.Hair001baked015_15.skeleton}
              morphTargetDictionary={
                nodes.Hair001baked015_15.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Hair001baked015_15.morphTargetInfluences
              }
            /> */}
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/avatar.gltf");
